var actualI18n;
var i18n = {};
i18n.es = {
  "name": "Ariadna Ercilla",
  "home": "Home ES",
  "services": "Servicios",
  "proyectos": "Proyectos",
  "curriculum": "Currículum",
  "contact": "Contacto",
  "welcomeMsg": "Hola! soy Ariadna",
  "subWelcome": "Diseñadora UX/UI",
  "discoverMore": "descubre más",
    "welcomePortfolio": "Bienvenidos a mi portfolio",
  "welcomeMe": "Me fascina entender al usuario, qué le mueve a actuar de cierta manera, desconcertarme cuando se confunden en ciertas acciones... Recopilar los datos de los usuarios y de las métricas, y realizar una constante mejora en cada proyecto e hipotesis.",
  "gurusTool": "Los gurús se equivocan, las métricas no.",
  "webDesign": "Diseño web",
  "mobileFirst": "Páginas web multidispositivos siguiendo la estrategia Mobile First.",
  "appDesign": "Diseño apps",
  "infoAppDesign": "Diseños centrados en apps, tanto para iOS como Android.",
  "userExperience": "Experiencia de usuario",
  "infoUserExperience": "Conocer al usuario. Prototipar, testear... Con software como Sketch o Axure.",
  "graficDesign": "Diseño Gráfico",
  "infoGraficDesign": "Branding, diseño editorial y retoque fotográfico",
  "webDeveloper": "Desarrollo web",
  "infoWebDeveloper": "HTML5, CSS3. trabajando con SASS y Git. Niveles iniciales de JavaScript y JQuery",
  "whatMore": "¿Que más?",
  "infoWhatMore": "Con ganas de aprender más sobre eyetracking y neuromárqueting!",
  "infoSmartcommerce": "Herramienta interna para gestionar y analizar una tienda online",
  "view_project": "ver proyecto",
  "infoXerpa": "Plataforma para realizar pedidos online.",
  "infoSmartlink": "Herramienta para analizar el estado de los productos de una marca en los supermercados",
  "infoMakeyoursuit": "Empresa del sector de moda de alta calidad",
  "infoPuntoyseguido": "Plataforma de intercambio de conocimiento entre creativos",
  "infoProcter": "Landing inicial de la tienda online de P&G",
  "viewAllProjects": "ver todos los proyectos",
  "knowledge": "Conocimientos",
  "aboutMe": "Sobre mi",
  "experience": "Experiencia",
  "studies": "Formación",
  "processWork": "Proceso de trabajo",
  "ImAriadna": "Soy Ariadna Ercilla y estoy especializada en el Diseño Web y en la Usabilidad. En mi día a día uso programas como Photoshop, Ilustrator, Sketch y Axure para crear desde wireframes iniciales hasta el prototipo final.",
  "technologicAboutMe": "También he trabajado enfocada en el desarrollo frontEnd, maquetando con HTML5 y CSS3 basándome en los estándares W3C. Utilizo Boostrap, el preprocesador SASS y GIT como controlador de versiones.",
  "knowMoreAboutMe": "saber más sobre mi",
  "love_ux": "Soy una apasionada de la usabilidad.",
  "webInspirations": "Soy una chica de Barcelona que tiene la suerte de disfrutar de su trabajo, soy una apasionada del diseño web y del píxel perfect! Frequentemente busco recursos e inspiración en webs como:",
  "ABPassion": "Me apasiona los test de usuario y los test A/B. Testear, cambiar, hacer hipotesis y probarlo con usuarios potenciales de nuestra web. Me da mucha adrenalina poder ver mis errores o hipotesis fallidas en vivo, y entender qué fue lo que no entendrieron o no les interesó.",
  "myHobbies": "Mis principales aficiones es ir a conciertos y a bailar, también me gusta salir de la ciudad y desconectar en la montaña.",
  "readWork": "Lee sobre mi experiencia laboral",
  "designFrontend": "Diseñadora UX-UI y Front-end.",
  "dateSmartCommerce": "Septiembre 2015 - actualidad",
  "functions": "Funciones",
  "conceptDesign": "Dieño y conceptualización de proyectos web",
  "responsiveDesign": "RWD (Responsive web Design)",
  "wireframePrototype": "Wireframes, prototipado y testeo de la web",
  "frontEndDeveloper": "Desarollo Front-end (HTML5 - CSS3)",
  "intern_graphic_design": "Becaria diseño gráfico",
  "use_img": "Uso de banco de imágenes",
  "photo_change": "Retoque fotográfico",
  "prepare_img_web": "Preparación de imágenes para web",
  "design_target": "Diseño de tarjetas, carteles, trítpicos",
  "design_web_grafic": "Diseñadora web y gráfica",
  "date_makeyoursuit": "Octubre 2014 - Octubre 2015",
  "web_redesign": "Rediseño de la web",
  "adapt_responsive": "Adaptación de la plataforma a versiones responsive",
  "design_banner": "Diseño de banners",
  "date_offerum": " Septiembre 2013 - Diciembre 2013",
  "date_sodexo": "Junio 2013 - Agosto 2013",
  "design_triptic": "Diseño de diferentes elementos corporativos del departamento: folletos, presentaciones, trípticos.",
  "design_newsletter": "Diseño de diferentes elementos web: banners, newsletters.",
  "see_my_work": "¿Quieres saber cómo trabajo?",
  "see_how_work": "Ver proceso de trabajo",
  "master_design_web": "Máster Diseño Web",
  "bau": "BAU - centro universitario de diseño de Barcelona.",
  "master_bau": "Máster de Diseño web centrado en cuatro ejes principales: Diseño web, Experiencia de Usuario (UX), Programación Frontend, Negocio y estrategia.",
  "design_degree": "Grado Diseño",
  "barcelona_university": "Universitat de Barcelona",
  "info_degree": "Carrera orientada a la formación integral del diseñador. Entender las necesidades del usuario, buscar soluciones óptimas y saberlas defender.",
  "show_steps_work": "Os quiero mostrar las diferentes fases que intento seguir en los proyectos que realizo, conjuntamente con los otros profesionales",
  "step_1": "Definición proyecto",
  "info_step_1": "Definir los requisitos y las funcionalidades del proyecto, hablando con el cliente y realizando entrevistas a usuarios.",
  "step_2": "Wireframes, prototipado y diseño",
  "info_step_2": "Validar conceptos, usabilidad y diseño a partir de diferentes herramientas con usuarios potenciales.",
  "step_3": "Maquetación y Programación",
  "info_step_3": "Programar la funcionalidad testeada anteriormente, para que funcione en todos los dispositivos, navegadores y sea accesible.",
  "step_4": "Testeo, lanzamiento y medición",
  "info_step_4": "Testear la correcta implementación del diseño antes del lanzamiento y medir el impacto en los usuarios de las nuevas funcionalidades.",
  "send_email": "¡Envíame un mensaje! ¿Crees que podemos trabajar juntos? ¿Quieres darme tu opinión de mis proyectos o simplemente decirme hola? ¡Aprovecha y envíame un mensaje, te responderé en breves!",
  "web_design": "Diseñadora web",
  "return": "volver",
  "info_tedclothing": "Startup de ropa full-print para jóvenes.",
  "info_saltin_banquin": "E-commerce de zapatos infantiles.",
  "info_boxeo": "E-commerce de ropa deportiva, especializado en ropa de boxeo.",
  "info_impremta": "Empresa que se abre al canal online, ofreciendo sus productos.",
  "trains": "trenes",
  "info_trains": "Maqueta de trenes, proyecto familiar.",
  "company": "Empresa",
  "mockups": "Mockups",
  "purpose": "Propuesta",
  "backend_text1": "SmartCommerce es una compañía tecnológica especializada en el sector de la distribución alimentaria online. Actualmente opera en Estados Unidos, España y Chile.",
  "backend_text2": "Uno de los servicios que ofrece es la creación y mantenimiento de tiendas online a grandes marcas de consumo como Nestlé, Procter&Gamble, Unilever o Cocacola. Se le proporciona al cliente una herramienta interna para gestionar stock, modificar la apariencia de la tienda o analizar las ventas.",
  "analyze_numbers": "Análisi de datos.",
  "create_campaign": "Proceso de creación de campaña",
  "campaigns_created": "Listado de todas las campañas creadas",
  "purpose_backend": "Rediseño de la herramienta interna que Smartcommerce ofrece a las empresas. Smartcommerce contaba con otra herramienta muy rudimentaria y poco intuitiva. La información no estaba bien jerarquizada, los clientes no entendían qué podían hacer y acababa repercutiendo en la empresa; nosotros teníamos que realizarles el mantenimiento interno de la plataforma por imposibilidad de utilización de los clientes.",
  "backend_steps": "Realicé el rediseño de la herramienta en 4 partes:",
  "backend_step1": "Análisi de las diferentes funcionalidades que existían, determinando qué funcionalidades eran interesantes y su valor para los clientes.",
  "backend_step2": "Entrevistas a los clientes para determinar qué funcionalidades eran más importantes, cómo las utilizaban y en qué acciones se confundían.",
  "backend_step3": "Realización de un prototipo funcional para testear con los clientes y construir una nueva herramienta fácil de usar, intuitiva y que responda a las necesidades reales de los clientes.",
  "backend_step4": "Maquetación de la web a nivel Front-End utilizando HTML5, CSS3, Boostrap y git.",
  "return_portfolio": "volver al portfolio",
  "purpose_jsuge": "J-SUGE es el proveedor de equipos textil profesional de muchos equipos de rugby, football, basketball y Boxeadores profesionales.",
  "purpose_jsuge2": "J-Suge nace con la finalidad de ser un ecommerce donde se pueda comprar ropa deportiva orientada a equipos.",
  "purpose_jsuge3": "La plataforma ha cambiado mucho des del diseño inicial, pero podeís consultar la web aquí: ",
  "img_jsuge1": "Catálogo de productos",
  "img_jsuge2": "Carrito de la compra",
  "img_jsuge3": "Area de usuario",
  "img_jsuge4": "Página de realización de pago",
  "img_jsuge5": "Web responsive",
  "printing": "Imprenta",
  "purpose_practic": " es una imprenta especializada a grandes impresiones para multinacionales. Destacan por su precio competitivo en el sector y quieren mejorar su visibilidad en el medio online",
  "img_imprenta1": "Home",
  "img_imprenta2": "Quiénes somos y nuestros valores",
  "img_imprenta3": "Solicitar presupuesto online",
  "img_imprenta4": "Página de contacto",
  "tecnics_used": "Técnicas utilizadas",
  "purpose_makeyoursuit1": "Makeyoursuit es una startup que se dedica a la comercialización de trajes y camisas hechos a medida a través de Internet.",
  "purpose_makeyoursuit2": "Cuenta con un proceso de personalización de sus prendas, para elegir telas, colores, formas, y añadir las medidas del cuerpo para llevar un traje encajado a las necesidades de cada cliente.",
  "img_makeyoursuit1": "Página inicial",
  "img_makeyoursuit2": "Catálogo de trajes",
  "img_makeyoursuit3": "Ficha producto",
  "img_makeyoursuit4": "Personalización traje",
  "makeyoursuit_steps": "Se analizan los KPI de la empresa y se definen 3 ejes iniciales para mejorar las conversiones de la misma.",
  "makeyoursuit_step1": "Rediseñar la página del carrito de la compra. Conseguimos disminuir el ratio de abandono al simplificar y dar seguridad en el proceso de pago.",
  "makeyoursuit_step2": "Diseñar landings específicas dependiendo de la búsqueda del usuario para ofrecer el producto que está buscando des del primer momento. Conseguimos aumentar las ventas en trajes específicos: bodas, trajes de 3 piezas.",
  "makeyoursuit_step3": "Mejorar el proceso de decisión del tejido, los complementos y la medición en casa. Conseguimos reduir el tiempo de desarollar esta tarea y disminuir el abandono durante el proceso; disminuir pasos de elección, indicar al usuario donde está en todo momento, qué puede hacer y cuantos pasos le quedan para finalizar la tarea.",
  "title_tecnic_makeyoursuit1": "Test usabilidad. ",
  "title_tecnic_makeyoursuit2": "Test A/B. ",
  "tecnic_makeyoursuit1": "Hicimos test de Usabilidad, donde los usarios tenían que realizar tareas cuotidianas. Detectamos diferentes inputs para mejorar en el proceso de compra.",
  "tecnic_makeyoursuit2": "Realizamos test A/B en las landings. Se provó el impacto de utilizar una imagen u otra, qué tipo de traje funcionaba mejor o las frases utilizadas. Se utilizó la herramienta Unbounce.",
  "info_procter1": "Procter&Gamble es una empresa estadouniense que contiene más de 300 marcas de gran consumo como Gillette, Ariel o Tampax.",
  "info_procter2": "Procter&Gamble dispone de una tienda online de la que se rediseñó su página de inicio.",
  "img_procter1": "Langind Procter&Gamble",
  "img_procter2": "Mapa de calor de la landing",
  "purpose_procter1": "Diseño de la home de la tienda online de P&G España, para mejorar las conversiones y disminuir el abandono en la landing.",
  "purpose_procter2": "Se analizó la landing que utilizaban y detectamos 3 principales problemas: 1. Los usuarios no entendían de qué trataba la web, 2. no encontraban los beneficios de utilizar su tienda en vez de comprar en los supermercados, 3. no sabían cómo acceder a los productos. A partir de estos inputs se diseñó la nueva landing y se testeó con el programa ",
  "purpose_procter3": "Nos permitió detectar fallos de usabilidad cómo: -algunos usuarios clicaban elementos no clicables, -la explicación de las ofertas estaba muy abajo de la landing y los usuarios no hacían tanto scroll.",
  "info_puntoyseguido1": "Puntoyseguido es un proyecto académico realizado con 3 compañeros.",
  "info_puntoyseguido2": "Puntoyseguido es un proyecto para creativos de Barcelona con pocos recursos económicos , quienes necesitan aprender de forma económica distintas funciones de un software que utilizan en el ámbito estudiantil y/o profesional. Puntoyseguido es una plataforma social creada a partir de anuncios de usuarios que permite el intercambio de conocimientos a cambio de una comida, una cena o una caña. La propuesta es facilitar el contacto entre creativos para intercambiar conocimientos a través de los cursos que ellos mismos crean, económicos , directos y con contenidos específicos útiles.",
  "img_puntoyseguido1": "Página inicial",
  "img_puntoyseguido2": "Cursos que ofrece la plataforma",
  "img_puntoyseguido3": "Ficha ampliada del curso, con información del profesor",
  "img_puntoyseguido4": "Perfil del profesor",
  "img_puntoyseguido5": "Información de la plataforma",
  "img_puntoyseguido6": "Imágenes de diferentes test de usabilidad y cardsorting.",
  "purpose_puntoyseguido1": "Creación de una plataforma para favorecer el conocimiento entre creativos de una manera colaborativa",
  "purpose_puntoyseguido2": "El proceso de trabajo se realizó en 3 ejes que se trabajaron con metodología agile y scrum:",
  "puntoyseguido_step1": "Investigar, entrevistar y definir a nuestro usuario y sus necesidades.",
  "puntoyseguido_step2": "Realizar el diseño de la plataforma y testear con usuarios las nuevas implementaciones.",
  "puntoyseguido_step3": "Maquetar a nivel frontend la plataforma para poder lanzarla.",
  "process_work": "Para más información sobre el proceso de trabajo: ",
  "memory_project": "Memoria del proyecto final de máster",
  "title_tecnic_puntoyseguido1": "Entrevistas y encuestas. ",
  "title_tecnic_puntoyseguido2": "Cardsorting. ",
  "title_tecnic_puntoyseguido3": "Test usabilidad. ",
  "tecnic_puntoyseguido1": "Se realizaron diferentes entrevistas para definir qué problemática tenían los creativos para formarse, y qué tipo de público le interesaría una propuesta como la nuestra.",
  "tecnic_puntoyseguido2": "Hicimos diferentes test donde los usuarios ordenaban la información de los cursos. Se obtuvo diferentes inputs en cuanto a qué información era imprescindible.",
  "tecnic_puntoyseguido3": "Cada una de las historias de usuario definidas en los sprints, se testearon y se modificaron acorde con las conclusiones de los test.",
  "saltin_banquin_info1": "Saltinbanquin se dedica a la venta de zapatos para niños en España. Se dedicaban también a la venta física, pero actualmente solamente se dedican al medio online. Destacan por ser zapatos de alta calidad y producidos en España.",
  "saltin_banquin_info2": "Se me encargó realizar un test de usabilidad, y proponer un rediseño de la plataforma.", 
  "saltin_banquin_info3": "Web antes del Rediseño: ",
  "img_saltinbanquin1": "Ficha de producto",
  "img_saltinbanquin2": "Catálogo",
  "img_saltinbanquin3": "Página de error",
  "img_saltinbanquin4": "Página de histórico de pedidos",
  "img_saltinbanquin5": "Página de contacto",
  "img_saltinbanquin6": "Página adaptable a todos los dispositivos",
  "purpose_saltinbanquin": "Se realizó un test de usabilidad para detectar los principales problemas con los que contaba la plataforma. Los más importantes eran:",
  "saltinbanquin_step1": "Mala jerarquización de la información y de las acciones prioritarias de la plataforma",
  "saltinbanquin_step2": "Diseño desactualizado, con imágenes y composiciones antiguas.",
  "saltinbanquin_step3": "Aumentar las conversiones desde tablet/móvil realizando un diseño adaptable a todos los dispositivos.",
  "smartlink_info1": "Smartlink es una herramienta para analizar el estado de los productos en los supermercados de las marcas de gran consumo. Analiza los productos que están fuera de estock, los precios en los supermercados, las imágenes, la posición en el catálogo...",
  "smartlink_info2": "Smartlink es la herramienta que facilita a las empresas tener conocimiento sobre cómo están sus productos en los supermercados online, y les ayuda a saber qué acciones realizar para mejorar su visibilidad en los supermercados, y por lo tanto, mejorar sus ventas.",
  "img_smartlink1": "Dashboard inicial que muestra el estado de las diferentes submarcas en las categorías más importantes.",
  "img_smartlink2": "Página para definir los productos más importantes y realizar un análisi más constante de ellos.",
  "img_smartlink3": "Página de análisi de los precios de los productos.",
  "purpose_smartlink1": "Rediseño de las pantallas. Se trabajó a partir de la versión anterior que había estado en funcionamiento más de 2 años. Esto nos permitió tener mucha información sobre cómo los clientes utilizaban la plataforma, las peticiones que nos iban planteando, qué problemas le veíamos (desde usabilidad, responsive, programación, contenido, etc..) y poder plantear una propuesta que mejorara todos los inputs obtenidos.",
  "purpose_smartlink2": "Mi contribución en el proyecto se resume en 3 pasos:",
  "smartlink_step1": "Analizar qué información era importante para los clientes y de qué manera mostrarla. Definir qué métricas, análisis, datos, etc... eran relevantes para las marcas.",
  "smartlink_step2": "Realizar un nuevo diseño mejorando la usabilidad de la herramienta.",
  "smartlink_step3": "Maquetar a nivel frontEnd la plataforma, con HTMl5, CSS3, Boostrap y git.",
  "tedclothing_info1": "Tedclothing es una startup que se dedica a la impresión y venta de ropa fullprint a través de internet.",
  "tedclothing_info2": "Cuenta con diferentes estilos de ropa colorida para jóvenes. Los estampados están orientados a captar el interés de los jóvenes con imágenes llamativas, transgresoras o mensajes graciosos o reivindicativos.", 
  "img_tedclothing1": "Página inicial",
  "img_tedclothing2": "Ficha de producto",
  "img_tedclothing3": "Página de contacto",
  "img_tedclothing4": "Página del carrito de la compra",
  "img_tedclothing5": "Versión móvil",
  "img_tedclothing6": "Diseño de camisetas",
  "purpose_tedclothing": "Se realizó el proyecto desde 0 y abordé muchos aspectos diferentes en el proceso de creación de la marca y su lanzamiento.",
  "tedclothing_step1": "Se realizó un estudio de mercado para determinar cual era el estilo de ropa qué interesaba a los jóvenes. Realizamos diferentes test para detectar qué tipo de prendas eran más atractivas para los jóvenes. Desde hacer entrevistas, mostrar diferentes banners con diferentes tipo de prendas, medir qué prendas eran más visualizadas y cuales más vendidas...",
   "tedclothing_step2": "Diseño de los estampados de las prendas.",
  "tedclothing_step3": "Realización de la identidad corporativa de la marca, desde el logotipo, elementos publicitarios, etc.",
  "tedclothing_step4": "Difusión de la marca en las redes sociales.",
  "tedclothing_step5": "Diseño de la tienda online. Se realizaron test de usuario para validar las funcionalidades.",
  "trenes_info1": "Maqueta de trenes. ",
  "trenes_info2": "Proyecto familiar de contruir y decorar una maqueta de 9 x 3 metros. Es un proyecto personal que empezó en el año 2000 a partir de la pasión de mi padre por los trenes. El se dedica a la electricidad de la maqueta y yo a la decoración.", 
  "img_trenes1": "Decoración de casa de pastores con huerta",
  "img_trenes2": "Conjunto de casas",
  "img_trenes3": "Ampliación huerta",
  "img_trenes4": "Estación máquinas de carbón",
  "img_trenes5": "Vía del tren con casa del vigilante",
  "img": "Imágenes",

  "xerpa_info1": "CityXerpa es una aplicación que se encarga de llevar cualquier producto de un punto a otro. Permite llevar comida de restaurantes, flores, productos del supermercado.. cualquier cosa que necesites a un lugar en concreto.",
  "xerpa_info2": "CityXerpa es una app que nace en Andorra y actualmente se está extendiendo en España.", 
  "img_xerpa1": "Home // Menú // Registro",
  "img_xerpa2": "Lista de restaurantes // Lista de productos con foto // Lista de productos sin foto",
  "img_xerpa3": "Error 404 // Pago // Pedido recibido",
  "purpose_xerpa1": "Diseño de la app para android y IOS.",
  "purpose_xerpa2": "Se realizaron diferentes wireframes de baja fidelidad para entender el proceso de compra y testar el proceso con los usuarios.Se realizaron los diseños de todas las pantallas y se creó un prototipo funcional para testear la aplicación.",
};




i18n.cat = {
   "name": "Ariadna Ercilla",
  "home": "Home ES",
  "services": "Serveis",
  "proyectos": "Projectes",
  "curriculum": "Currículum",
  "contact": "Contacte",
  "welcomeMsg": "Hola! sóc l'Ariadna",
  "subWelcome": "Disseñadora UX/UI",
  "discoverMore": "descobreix més",
  "welcomePortfolio": "Benvinguts al meu portfoli",
  "welcomeMe": "Em fascina entendre l'usuari, que el mou a actuar de certa manera, desconcertar-me quan es confonen realitzant certes accions... Recollir dades dels usuaris i de les mètriques i realitar una constant millora en cada hipòtesis i projecte.",
  "gurusTool": "Els gurús s'equivoquen, les mètriques no.",
  "webDesign": "Disseny web",
  "mobileFirst": "Págines web multidispositiu seguint la estratègia de Mobile First.",
  "appDesign": "Disseny d'apps",
  "infoAppDesign": "Disseny centrat en apps, tant per IOS com per Android.",
  "userExperience": "Experiència d'usuari",
  "infoUserExperience": "Conèixer l'usuari. Prototipar, testejar.. Amb softwares com Sketch o Axure.",
  "graficDesign": "Disseny Gràfic",
  "infoGraficDesign": "Branding, disseny editorial i retoc fotogràfic",
  "webDeveloper": "Desenvolupament web",
  "infoWebDeveloper": "HTML5, CSS3. Treballant amb SASS i Git. Nivells inicials de Javascript i Jquery",
  "whatMore": "Què més?",
  "infoWhatMore": "Amb ganes d'aprendre sobre eyetracking i neuromàrqueting!",
  "infoSmartcommerce": "Eina interna per gestionar i analitzar una botiga online",
  "view_project": "veure projecte",
  "infoXerpa": "Plataforma per realitzar comandes online.",
  "infoSmartlink": "Eina per analitzar l'estat dels productes d'una marca als supermercats",
  "infoMakeyoursuit": "Empresa del sector de moda d'alta qualitat",
  "infoPuntoyseguido": "Plataforma d'intercanvi de coneixements entre creatius",
  "infoProcter": "Landing inicial de la botiga online de P&G",
  "viewAllProjects": "veure tots els projectes",
  "knowledge": "Coneixements",
  "aboutMe": "About me",
  "experience": "Experiència",
  "studies": "Formació",
  "processWork": "Procés de treball",
  "ImAriadna": "Sóc l'Ariadna Ercilla i estic especialitzada en el Disseny Web i la Usabilitat. En el meu dia a dia utiltzo programes com Phtoshop, Ilustrator, Sketch i Axure per crear des de wireframes inicials fins el prototip final.",
  "technologicAboutMe": "També he treballat enfocada en el desenvolupament FrontEnd, maquetant amb HTML5 i CSS3 basant-me en els estàndars W3C. Utilitzo Boostrap, el preprocessador SASS i Git com a controlador de versions.",
  "knowMoreAboutMe": "saber més sobre mi",
  "love_ux": "Sóc una apasionada de la usabilitat.",
  "webInspirations": "Sóc una noia de Barcelona que te la sort de disfrutar de la seva feina, sóc una apasionada del disseny web i del píxel perfect! Freqüèntment busco recursos i inspracions en webs com:",
  "ABPassion": "M'apassionen els test d'usuari i els test A/B. Testejar, canviar i fer hipòtesis i provar-ho amb usuaris potencials de la nostra web. Em dona molta adrenalina poder veure els meus error o hipòtesis fallides en viu i entendre què va ser el que no van entendre o interessar.",
  "myHobbies": "Les meves principals aficions son anar a concerts i ballar, també m'agrada sortir de la ciutat i deconectar a la montanya.",
  "readWork": "Llegeix sobre la meva experiència laboral",
  "designFrontend": "Dissenyadora UX-UI i Front-end.",
  "dateSmartCommerce": "Setembre 2015 - actualitat",
  "functions": "Funcions",
  "conceptDesign": "Disseny i conceptualització de projectes web",
  "responsiveDesign": "RWD (Responsive web Design)",
  "wireframePrototype": "Wireframes, prototipat i testeig de la web",
  "frontEndDeveloper": "Desenvolupament Front-end (HTML5 - CSS3)",
  "intern_graphic_design": "Becaria disseny gráfic",
  "use_img": "Utilització de banc d'imatges",
  "photo_change": "Retoc fotogràfic",
  "prepare_img_web": "Preparació d'imatges per la web",
  "design_target": "Disseny de targetes, cartells, tríptics",
  "design_web_grafic": "Dissenyadora web i gráfica",
  "date_makeyoursuit": "Octubre 2014 - Octubre 2015",
  "web_redesign": "Redisseny de la web",
  "adapt_responsive": "Adaptació de la plataforma a versions responsives",
  "design_banner": "Disseny de banners",
  "date_offerum": " Setembre 2013 - Desembre 2013",
  "date_sodexo": "Juny 2013 - Agost 2013",
  "design_triptic": "Disseny de diferents elements corporatius del departament: folletons, presentacions, tríptics.",
  "design_newsletter": "Disseny de diferents elements web: banners, newsletters.",
  "see_my_work": "¿Vols saber més sobre com treballo?",
  "see_how_work": "Veure procés de treball",
  "master_design_web": "Máster Disseny Web",
  "bau": "BAU - centre universitari de Disseny de Barcelona.",
  "master_bau": "Màster de Disseny Web centrat en quatre eixos principals: Disseny Web, Experiencia d'Usuari (UX), Programació FrontEnd, Negoci i estratègia.",
  "design_degree": "Grau Disseny Web",
  "barcelona_university": "Universitat de Barcelona",
  "info_degree": "Carrera orientada a la formació integral del dissenyador. Entendre les necessitats del usuari, buscar solucions òptimes i saber defensar-les.",
  "show_steps_work": "Us vull mostrar les diferents fases que intento seguir en els projectes que realitzo, conjuntament amb els altres professionals",
  "step_1": "Definició projecte",
  "info_step_1": "Definir els requisits i les funcions del projecte, parlant amb el client i realitzant entrevistes d'usuari.",
  "step_2": "Wireframes, prototipat i disseny",
  "info_step_2": "Validar conceptes, usabilitat i disseny a partir de diferents eines amb els usuaris potencials.",
  "step_3": "Maquetació y Programació",
  "info_step_3": "Programar la funcionalitat testejada anteriorment, perque funcioni en tots els dispositius, navegadors i sigui accessible.",
  "step_4": "Testeig, llançament i medició",
  "info_step_4": "Testejar la correcta implementació del disseny abans del seu llançament i medir l'impacte en els usuaris de les noves funcionalitats.",
  "send_email": "¡Envia'm un missatge! Creus que podriem treballar junts? Vols donar-me la teva opinió dels meus projectes o simplement dir-me hola? Aprofita i envia'm un missatge, et respondrñe en breus!",
  "web_design": "Dissenyadora Web",
  "return": "tornar",
  "info_tedclothing": "Startup de roba full-print per joves.",
  "info_saltin_banquin": "E-commerce de sabates infantils.",
  "info_boxeo": "E-commerce de roba esportiva, especialitzada en roba de boxa.",
  "info_impremta": "Empresa que s'expandeix al canal online, oferint els seus productes.",
  "trains": "trens",
  "info_trains": "Maqueta de trens, projecte familiar.",
  "company": "Empresa",
  "mockups": "Mockups",
  "purpose": "Proposta",
  "backend_text1": "SmartCommerce és una companyia tecnològica especialitzada en el sector de la distribució alimentària online. Actualment opera a Estats Units, Espanya i Xile.",
  "backend_text2": "Un dels serveis que ofereix és la creació i manteniment de botigues onlines de grans marques de consum alimentari com Nestlé, Procter&Gamble, Unilever o Cocacola. Se'ls proporciona una eina interna per gestinar stock, modificar la aparença de la botiga o analitzar vendes.",
  "analyze_numbers": "Anàlisi de dades.",
  "create_campaign": "Procés de creació de campanyes",
  "campaigns_created": "Llistat de totes les campanyes creades",
  "purpose_backend": "Redisseny de la eina interna que SmartCommerce ofereix a les empreses. SmartCommerce comptava amb una atra eina molt rudimentaria i poc intuitiva. La informació no estava ben jerarquitzada, els clients no entenien què podien fer i acabava repercutint en la empresa; nosaltres haviem de realitzar el manteniment intern de la plataforma per la impossibilitat d'utilització dels clients.",
  "backend_steps": "Vaig realitzar el redisseny de la eina en 4 parts:",
  "backend_step1": "Ànalisi de les diferents funcionalitats que existien, determinant quines funcionalitats eren interessants i el seu valor pels usuaris.",
  "backend_step2": "Entrevistes als clients per determinar quines funcionalitats eren importants, com les utilitzaven i en la realització de quines accions es confonien.",
  "backend_step3": "Realització d'un prototip funcional per testejar amb els clients i contruir una nova eina fàcil d'utilitzar, intuitiva i que respon a les necessitats reals dels clients.",
  "backend_step4": "Maquetació de la web a nivell FrontEnd utilitzant HTML5, CSS3, Boostrap y GIT.",
  "return_portfolio": "tornar al portfoli",
  "purpose_jsuge": "J-SUGE és el proveidor d'equips tèxtils professionals de molts equips de rugby, futbol, basquet i boxejadors professionals.",
  "purpose_jsuge2": "J-Suge neix amb la finalitat de ser un ecommerce a on es pot comprar roba esportiva orientada a equips.",
  "purpose_jsuge3": "La plataforma ha canviat molt des del disseny original, pero podeu consultar la web aquí: ",
  "img_jsuge1": "Catàleg de productes",
  "img_jsuge2": "Carro de la compra",
  "img_jsuge3": "Àrea d'usuari",
  "img_jsuge4": "Pàgina de realització del pagament",
  "img_jsuge5": "Web responsive",
  "printing": "Impremta",
  "purpose_practic": " és una impremta especialitzada a grans impressions per multinacionals. Destaquen pel seu preu competitiu en el sector i vlen millorar la seva visibilitat en el medi online",
  "img_imprenta1": "Home",
  "img_imprenta2": "Qui som i els nostresvalors",
  "img_imprenta3": "Sol·licitar pressupost online",
  "img_imprenta4": "Pàgina de contacte",
  "tecnics_used": "Tècniques utilitzades",
  "purpose_makeyoursuit1": "Makeyoursuit és una startup que es dedica a la comercialització de vestits i camises a mida a través d'internet.",
  "purpose_makeyoursuit2": "Compte amb un procés de personalització de les seves peces, per elegir talla, colors, formes i afegir les mides del cos per portar un vestit encaixat al cos i necessitats del client.",
  "img_makeyoursuit1": "Pàgina inicial",
  "img_makeyoursuit2": "Catàleg de vestits",
  "img_makeyoursuit3": "Fitxa producte",
  "img_makeyoursuit4": "Personalizació vestits",
  "makeyoursuit_steps": "S'analitzen els KPI de l'empresa i es defineixen 3 eixos inicials per millorar les seves conversions.",
  "makeyoursuit_step1": "Redissenyar la pàgina del carro de la compra. Vam conseguir disminuir el ratio d'abandonament al simplicar el procés i donar major seguretat en el procés de pagament.",
  "makeyoursuit_step2": "Dissenyar landings específiques depenent de la búsqueda del usuari per oferir el producte que estan buscant des del primer moment. Vam conseguir aumentar les vendes en vestits específics: casaments i vestits de 3 peces.",
  "makeyoursuit_step3": "Millorar el procés de decisió del teixit, els complements i la medició a casa. Vam aconseguir reduir el temps de desenvolupar aquesta tasca i disminuir l'abandonament durant el procés; disminuir els passos d'elecció, indicar al usuari a on està en tot moment, què pot fer i quants passos li queden per finalitzar la tasca.",
  "title_tecnic_makeyoursuit1": "Test d'usabilitat. ",
  "title_tecnic_makeyoursuit2": "Test A/B. ",
  "tecnic_makeyoursuit1": "Vam fer test d'usabilitat a on els usuaris havien de realitzar tasques quotidianes. Vam detectar diferents inputs per millorar el procés de compra.",
  "tecnic_makeyoursuit2": "Vam realitzar test A/B a les landings. Es va testejar l'impacte d'utilitzar una imatge o una altra, quin tipus de vestit funcionava millor o les frases a utilitzar. Esva utilitzar l'eina Unbounce.",
  "info_procter1": "Procter&Gamble és una empresa d'Estats Units que conté més de 300 marques de gran consum com Gillette, Arial o Tampax.",
  "info_procter2": "Procter&Gamble disposa d'una botiga online de la que es va redissenyar la seva pàgina d'inici",
  "img_procter1": "Langind Procter&Gamble",
  "img_procter2": "Mapa de calor de la landing",
  "purpose_procter1": "Disseny de la home de la botiga online de P&G Espanya, per millorar les conversions i disminuir l'abandonament en la pàgina d'inici.",
  "purpose_procter2": "Es va analitzar la landing que utilitzaven anteriorment i vam detectar 3 principals problemes: 1. Els usuaris no entenien de qué tractava la web, 2. no trobaven els beneficis d'utilitzar aquesta botiga en comptes de comprar directament als supermercats, 3. no sabien com accedir als productes. A partir d'aquests inputs es va dissenyar la nova landing i es va testehar amb el programa ",
  "purpose_procter3": "Ens va permetre detectar errors d'usabilitat com: -alguns usuaris clicaven a elements no clicables, -l'explicació de les ofertes estava molt abaix de la pàgina i els usuaris no feien scroll.",
  "info_puntoyseguido1": "Puntoyseguido és un projecte acadèmic realitzat amb 3 companys.",
  "info_puntoyseguido2": "Puntoyseguido és un projecte per creatius de Barcelona amb pocs recursos econòmics, que necessiten aprendre de manera econòmica diferents funcions d'un software que utilitzen el l'àmbit estudiantil i/o professional. Puntoyseguido és una plataforma social creada a partir d'anuncis d'usuaris que permeten el coneixement a través de cursos que ells mateixos creen, econòmics, directes i amb contingut específic útil.",
  "img_puntoyseguido1": "Pàgina inicial",
  "img_puntoyseguido2": "Cursos que ofereix la plataforma",
  "img_puntoyseguido3": "Fitxa ampliada del curs, amb informació del professor",
  "img_puntoyseguido4": "Perfil del professor",
  "img_puntoyseguido5": "Informació de la plataforma",
  "img_puntoyseguido6": "Imatges de diferents test d'usabilitat i cardsorting.",
  "purpose_puntoyseguido1": "Creació d'una plataforma per afavorir el coneixement entre creatius d'una manera col·laborativa",
  "purpose_puntoyseguido2": "El procés de treball es va realitzar en 3 eixos que es van treballar amb metodologies àgils i scrum:",
  "puntoyseguido_step1": "Investigar, entrevistar y definir a nuestro usuario y sus necesidades.",
  "puntoyseguido_step2": "Realitzar el disseny de la plataforma i testejar amb usuaris les noves implementacions.",
  "puntoyseguido_step3": "Maquetar a nivell FrontEnd la plataforma per poder llançar-la.",
  "process_work": "Per més informació sobre el procés de treball: ",
  "memory_project": "Memòria del projecte final de màster",
  "title_tecnic_puntoyseguido1": "Entrevistes i enquestes. ",
  "title_tecnic_puntoyseguido2": "Cardsorting. ",
  "title_tecnic_puntoyseguido3": "Test usabilitat. ",
  "tecnic_puntoyseguido1": "Es van realitzar diferents entrevistes per definir quina problemàtica tenien els creatius per formar-se, i quin tipus de públic els interessaría una proposta com la nostra.",
  "tecnic_puntoyseguido2": "Vam fer diferents test a on els usuaris ordenaven la informació dels cursos. Es va obtenir diferents inputs en quant a quina informació era impressindible mostrar.",
  "tecnic_puntoyseguido3": "Cada una de les històries d'usuari definies en els sprints, es van testejar i es van modificar en funció de les conclusions dels tests.",
  "saltin_banquin_info1": "Saltinbanquin es dedica a la venda de sabates per infants a Espanya. Es dedicaven a la venda física, pero actualment únicament venen al medi online. Destaquen per ser sabates d'alta qualitat i produides a Espanya.",
  "saltin_banquin_info2": "Se'm va encarregar realitzar un test d'usabilitat i proposar un redisseny de la plataforma.", 
  "saltin_banquin_info3": "Web abans del redisseny: ",
  "img_saltinbanquin1": "Fitxa del producte",
  "img_saltinbanquin2": "Catàleg",
  "img_saltinbanquin3": "Pàgina d'error",
  "img_saltinbanquin4": "Pàgina d'històric de comandes",
  "img_saltinbanquin5": "Pàgina de contacte",
  "img_saltinbanquin6": "Pàgina adaptable a tots els dispositius",
  "purpose_saltinbanquin": "Es va realitzar un test d'usabilitat per detectar els principals problemes de la web. Els més importants eren:",
  "saltinbanquin_step1": "Mala jerarquització de l'informació i de les accions prioritaries de la plataforma",
  "saltinbanquin_step2": "Disseny desactualitzat, amb imatges i composicions antigues.",
  "saltinbanquin_step3": "Aumentar les conversions des de tablet/mòbil realitzant un disseny adaptable a tots els dispositius.",
  "smartlink_info1": "Smartlink és una eina per analitzar l'estat dels productes en els supermercats de les marques de gran consum. Analitza els productes que estan fora d'estock, els preus en cada supermercat, les imatges, la posició dels productes al catàleg...",
  "smartlink_info2": "Smartlink és la eina que facilita a les empreses tenir un coneixement sobre com estan els seus productes en els supermercats online, o els ajuda a saber quines accions realitzar per aumentar la seva visibilitat en els supermercats, i per tant, millorar les seves vendes.",
  "img_smartlink1": "Dashboard inicial que mostra l'estat de les diferents submarques en les categories més importants.",
  "img_smartlink2": "Pàgina per definir els productes més importants i realitzar un anàlisis més constant d'ells.",
  "img_smartlink3": "Pàgina d'anàlisi dels preus dels productes.",
  "purpose_smartlink1": "Redisseny de les pantalles. Es va treballar a partir de la versió anterior que havia estat en funcionament durant més de 2 anys. Això ens va permetre tenir molta informació sobre com els clients utilitzaven la plataforma, les peticions que ens havien anat demanant els clients, quines mencances sabiem que tenia la plataforma (des de usabilitat, responsive, programació, contingut, etc..) i poder plantejar una proposta per millorar tots els inputs obtinguts.",
  "purpose_smartlink2": "La meva contribució al projecte es resumeix en 3 passos:",
  "smartlink_step1": "Analitzar quina informació era important pels clients i de quina manera mostrar-la. Definir quines mètriques, anàlisi, dades, etc.. eren rellevants per les marques.",

  
  "smartlink_step2": "Realitzar un nou disseny millorant la usabilitat de l'eina.",
  "smartlink_step3": "Maquetar a nivell FrontEnd la plataforma, amb HTML5, CSS3, Boostrap i GIT.",
  "tedclothing_info1": "Tedclothing és una startup que es dedica a la impressió i venda de roba fullprint a través d'internet.",
  "tedclothing_info2": "Compte amb diferents estils de roba colorida per joves. Els estampats estan orientats a captar l'interès dels joves amb imatges vistoses, transgressores o missatges graciosos o reivindicatius.", 
  "img_tedclothing1": "Pàgina inicial",
  "img_tedclothing2": "Fitxa de producte",
  "img_tedclothing3": "Pàgina de contacte",
  "img_tedclothing4": "Pàgina del carro de la compra",
  "img_tedclothing5": "Versió mòbil",
  "img_tedclothing6": "Disseny de samarretes",
  "purpose_tedclothing": "Es va realitzar un projecte des de 0 i vaig abordar molts aspectes diferents en el procés de creació de la marca i del seu llançament.",
  "tedclothing_step1": "Es va realitzar un estudi de mercat per determinar quin era l'estil de roba que interessava als joves. Vam realitzar test per detectar quin tipus de peces eren més atractives pels joves. Des de fer entrevistes, mostrar diferents banners amb diferents estils de roba, medir quines peces eren més visualitzades i quines mes venudes...",
   "tedclothing_step2": "Disseny dels estampats de les peces.",
  "tedclothing_step3": "Realització de la identitat corporativa de la marca, des del logotip, elements publicitaris, etc.",
  "tedclothing_step4": "Difusió de la marca en xarxes socials.",
  "tedclothing_step5": "Disseny de la botiga online. Es van realitzar test d'usuari per validar les funcionalitats.",
  "trenes_info1": "Maqueta de trens. ",
  "trenes_info2": "Projecte familiar de construir i decorar una maqueta de 9 x 3 metres. És un projecte personal que va començar l'any 2000 a partir de la passió del meu pare pels trens. Ell es dedica a la electricitat de la maqueta i jo a la decoració.", 
  "img_trenes1": "Decoració de la casa dels pastors amb un hort",
  "img_trenes2": "Conjunt de cases",
  "img_trenes3": "Ampliació del hort",
  "img_trenes4": "Estació màquines de carbó",
  "img_trenes5": "Via del tren amb casa del vigilant",
  "img": "Imatges",
  "xerpa_info1": "CityXerpa és una aplicació que s'encarrega de portar qualsevol producte d'un punt a un altre. Permet portar menjar de restaurants, flors, productes del supermercat... qualsevol cosa que es necessita a un lloc en concret.",
  "xerpa_info2": "CityXerpa és una app que neix a Andorra i actualment s'està extenent a Espanya.", 
  "img_xerpa1": "Home // Menú // Registre",
  "img_xerpa2": "Llista de restaurants // Llista de productes amb foto // Llista de productes sense foto",
  "img_xerpa3": "Error 404 // Pagament // Comanda rebuda",
  "purpose_xerpa1": "Disseny de la app per android i IOS.",
  "purpose_xerpa2": "Es van realitzar diferents wireframes de baixa fidelitat per entendre el procés de compra i testejar el procés amb usuaris. Es van realitzar dissenys de totes les pantalles i es va crear un prototip funcional per testejar l'aplicació.",
};

i18n.en = {
  "name": "Ariadna Ercilla",
  "home": "Home ES",
  "services": "Services",
  "proyectos": "Projects",
  "curriculum": "Resume",
  "contact": "Contact",
  "welcomeMsg": "Hi! It's Ariadna",
  "subWelcome": "UX/UI Designer",
  "discoverMore": "discover more",
    "welcomePortfolio": "Welcome to my portfolio",
  "welcomeMe": "I am fascinated to understand the user, what moves him to act in a certain way, disconcerting me when they are confused in certain actions ... To gather the data of the users and of the metrics, and to make a constant improvement in each project and hypothesis.",
  "gurusTool": "Gurus are wrong, metrics are not.",
  "webDesign": "Web Designer",
  "mobileFirst": "Multi-device web pages following the Mobile First strategy.",
  "appDesign": "Apps Design",
  "infoAppDesign": "Designs focus in apps, Diseños centrados en apps, for both iOS and Android.",
  "userExperience": "User Experience",
  "infoUserExperience": "Know the user. Prototype, test.. wth software like Sketch or Axure.",
  "graficDesign": "Graphic Design",
  "infoGraficDesign": "Branding, editorial web and photo retouching",
  "webDeveloper": "Web developer",
  "infoWebDeveloper": "HTML5, CSS3. working with SASS and GIT. Initial levels of Javascript and JQuery.",
  "whatMore": "What's more?",
  "infoWhatMore": "Wanting to learn more about eye tracking and neuromarketing!",
  "infoSmartcommerce": "Internal tool to manage and analyze a online website.",
  "view_project": "see project",
  "infoXerpa": "Online Ordering Platform.",
  "infoSmartlink": "Internal tool to analyze the product status of a concret brand in the retailers.",
  "infoMakeyoursuit": "Company of the sector of fashion of high quality",
  "infoPuntoyseguido": "Platform of knowledge exchange between creatives.",
  "infoProcter": "Initial landing of P&G online shop.",
  "viewAllProjects": "see all projects",
  "knowledge": "Knowledge",
  "aboutMe": "About me",
  "experience": "Experience",
  "studies": "Training",
  "processWork": "Working process",
  "ImAriadna": "I am Ariadna Ercilla and I am specialized in Web Design and Usability. In my day to day I use programs like Photoshop, Illustrator, Sketch and Axure to create from initial wireframes to the final prototype.",
  "technologicAboutMe": "I have also worked on frontEnd development, layouting with HTML5 and CSS3 based on W3C standards. I use Boostrap, the SASS and GIT preprocessor as a version driver.",
  "knowMoreAboutMe": "Know more about me",
  "love_ux": "I'm passionate of usability.",
  "webInspirations": "I'm a girl from Barcelona who is lucky to enjoy her work, I'm passionate about web design and the perfect pixel! I often look for resources and inspiration in webs like:",
  "ABPassion": "I'm passionated about user test and a/B testing. Test, change, Hipothesize and test it with potencial users of our webs. It gives me a lot of adrenaline to be able to see my mistakes or failed hypotheses, and to understand what it was the problem and what is that users don't understant or don't interested them.",
  "myHobbies": "My main hobbies are going to concerts and dancing, I also like to get out of the city and disconnect in the mountains.",
  "readWork": "Read about my work experience.",
  "designFrontend": "UX-UI Designer and Front-end.",
  "dateSmartCommerce": "September 2015 - present",
  "functions": "Functions",
  "conceptDesign": "Design and conceptualization of web projects",



  
  "responsiveDesign": "RWD (Responsive web Design)",
  "wireframePrototype": "Wireframes, prototipado y testeo de la web",
  "frontEndDeveloper": "Desarollo Front-end (HTML5 - CSS3)",
  "intern_graphic_design": "Becaria diseño gráfico",
  "use_img": "Uso de banco de imágenes",
  "photo_change": "Retoque fotográfico",
  "prepare_img_web": "Preparación de imágenes para web",
  "design_target": "Diseño de tarjetas, carteles, trítpicos",
  "design_web_grafic": "Diseñadora web y gráfica",
  "date_makeyoursuit": "Octubre 2014 - Octubre 2015",
  "web_redesign": "Rediseño de la web",
  "adapt_responsive": "Adaptación de la plataforma a versiones responsive",
  "design_banner": "Diseño de banners",
  "date_offerum": " Septiembre 2013 - Diciembre 2013",
  "date_sodexo": "Junio 2013 - Agosto 2013",
  "design_triptic": "Diseño de diferentes elementos corporativos del departamento: folletos, presentaciones, trípticos.",
  "design_newsletter": "Diseño de diferentes elementos web: banners, newsletters.",
  "see_my_work": "¿Quieres saber cómo trabajo?",
  "see_how_work": "Ver proceso de trabajo",
  "master_design_web": "Máster Diseño Web",
  "bau": "BAU - centro universitario de diseño de Barcelona.",
  "master_bau": "Máster de Diseño web centrado en cuatro ejes principales: Diseño web, Experiencia de Usuario (UX), Programación Frontend, Negocio y estrategia.",
  "design_degree": "Grado Diseño",
  "barcelona_university": "Universitat de Barcelona",
  "info_degree": "Carrera orientada a la formación integral del diseñador. Entender las necesidades del usuario, buscar soluciones óptimas y saberlas defender.",
  "show_steps_work": "Os quiero mostrar las diferentes fases que intento seguir en los proyectos que realizo, conjuntamente con los otros profesionales",
  "step_1": "Definición proyecto",
  "info_step_1": "Definir los requisitos y las funcionalidades del proyecto, hablando con el cliente y realizando entrevistas a usuarios.",
  "step_2": "Wireframes, prototipado y diseño",
  "info_step_2": "Validar conceptos, usabilidad y diseño a partir de diferentes herramientas con usuarios potenciales.",
  "step_3": "Maquetación y Programación",
  "info_step_3": "Programar la funcionalidad testeada anteriormente, para que funcione en todos los dispositivos, navegadores y sea accesible.",
  "step_4": "Testeo, lanzamiento y medición",
  "info_step_4": "Testear la correcta implementación del diseño antes del lanzamiento y medir el impacto en los usuarios de las nuevas funcionalidades.",
  "send_email": "¡Envíame un mensaje! ¿Crees que podemos trabajar juntos? ¿Quieres darme tu opinión de mis proyectos o simplemente decirme hola? ¡Aprovecha y envíame un mensaje, te responderé en breves!",
  "web_design": "Diseñadora web",
  "return": "volver",
  "info_tedclothing": "Startup de ropa full-print para jóvenes.",
  "info_saltin_banquin": "E-commerce de zapatos infantiles.",
  "info_boxeo": "E-commerce de ropa deportiva, especializado en ropa de boxeo.",
  "info_impremta": "Empresa que se abre al canal online, ofreciendo sus productos.",
  "trains": "trenes",
  "info_trains": "Maqueta de trenes, proyecto familiar.",
  "company": "Empresa",
  "mockups": "Mockups",
  "purpose": "Propuesta",
  "backend_text1": "SmartCommerce es una compañía tecnológica especializada en el sector de la distribución alimentaria online. Actualmente opera en Estados Unidos, España y Chile.",
  "backend_text2": "Uno de los servicios que ofrece es la creación y mantenimiento de tiendas online a grandes marcas de consumo como Nestlé, Procter&Gamble, Unilever o Cocacola. Se le proporciona al cliente una herramienta interna para gestionar stock, modificar la apariencia de la tienda o analizar las ventas.",
  "analyze_numbers": "Análisi de datos.",
  "create_campaign": "Proceso de creación de campaña",
  "campaigns_created": "Listado de todas las campañas creadas",
  "purpose_backend": "Rediseño de la herramienta interna que Smartcommerce ofrece a las empresas. Smartcommerce contaba con otra herramienta muy rudimentaria y poco intuitiva. La información no estaba bien jerarquizada, los clientes no entendían qué podían hacer y acababa repercutiendo en la empresa; nosotros teníamos que realizarles el mantenimiento interno de la plataforma por imposibilidad de utilización de los clientes.",
  "backend_steps": "Realicé el rediseño de la herramienta en 4 partes:",
  "backend_step1": "Análisi de las diferentes funcionalidades que existían, determinando qué funcionalidades eran interesantes y su valor para los clientes.",
  "backend_step2": "Entrevistas a los clientes para determinar qué funcionalidades eran más importantes, cómo las utilizaban y en qué acciones se confundían.",
  "backend_step3": "Realización de un prototipo funcional para testear con los clientes y construir una nueva herramienta fácil de usar, intuitiva y que responda a las necesidades reales de los clientes.",
  "backend_step4": "Maquetación de la web a nivel Front-End utilizando HTML5, CSS3, Boostrap y git.",
  "return_portfolio": "volver al portfolio",
  "purpose_jsuge": "J-SUGE es el proveedor de equipos textil profesional de muchos equipos de rugby, football, basketball y Boxeadores profesionales.",
  "purpose_jsuge2": "J-Suge nace con la finalidad de ser un ecommerce donde se pueda comprar ropa deportiva orientada a equipos.",
  "purpose_jsuge3": "La plataforma ha cambiado mucho des del diseño inicial, pero podeís consultar la web aquí: ",
  "img_jsuge1": "Catálogo de productos",
  "img_jsuge2": "Carrito de la compra",
  "img_jsuge3": "Area de usuario",
  "img_jsuge4": "Página de realización de pago",
  "img_jsuge5": "Web responsive",
  "printing": "Imprenta",
  "purpose_practic": " es una imprenta especializada a grandes impresiones para multinacionales. Destacan por su precio competitivo en el sector y quieren mejorar su visibilidad en el medio online",
  "img_imprenta1": "Home",
  "img_imprenta2": "Quiénes somos y nuestros valores",
  "img_imprenta3": "Solicitar presupuesto online",
  "img_imprenta4": "Página de contacto",
  "tecnics_used": "Técnicas utilizadas",
  "purpose_makeyoursuit1": "Makeyoursuit es una startup que se dedica a la comercialización de trajes y camisas hechos a medida a través de Internet.",
  "purpose_makeyoursuit2": "Cuenta con un proceso de personalización de sus prendas, para elegir telas, colores, formas, y añadir las medidas del cuerpo para llevar un traje encajado a las necesidades de cada cliente.",
  "img_makeyoursuit1": "Página inicial",
  "img_makeyoursuit2": "Catálogo de trajes",
  "img_makeyoursuit3": "Ficha producto",
  "img_makeyoursuit4": "Personalización traje",
  "makeyoursuit_steps": "Se analizan los KPI de la empresa y se definen 3 ejes iniciales para mejorar las conversiones de la misma.",
  "makeyoursuit_step1": "Rediseñar la página del carrito de la compra. Conseguimos disminuir el ratio de abandono al simplificar y dar seguridad en el proceso de pago.",
  "makeyoursuit_step2": "Diseñar landings específicas dependiendo de la búsqueda del usuario para ofrecer el producto que está buscando des del primer momento. Conseguimos aumentar las ventas en trajes específicos: bodas, trajes de 3 piezas.",
  "makeyoursuit_step3": "Mejorar el proceso de decisión del tejido, los complementos y la medición en casa. Conseguimos reduir el tiempo de desarollar esta tarea y disminuir el abandono durante el proceso; disminuir pasos de elección, indicar al usuario donde está en todo momento, qué puede hacer y cuantos pasos le quedan para finalizar la tarea.",
  "title_tecnic_makeyoursuit1": "Test usabilidad. ",
  "title_tecnic_makeyoursuit2": "Test A/B. ",
  "tecnic_makeyoursuit1": "Hicimos test de Usabilidad, donde los usarios tenían que realizar tareas cuotidianas. Detectamos diferentes inputs para mejorar en el proceso de compra.",
  "tecnic_makeyoursuit2": "Realizamos test A/B en las landings. Se provó el impacto de utilizar una imagen u otra, qué tipo de traje funcionaba mejor o las frases utilizadas. Se utilizó la herramienta Unbounce.",
  "info_procter1": "Procter&Gamble es una empresa estadouniense que contiene más de 300 marcas de gran consumo como Gillette, Ariel o Tampax.",
  "info_procter2": "Procter&Gamble dispone de una tienda online de la que se rediseñó su página de inicio.",
  "img_procter1": "Langind Procter&Gamble",
  "img_procter2": "Mapa de calor de la landing",
  "purpose_procter1": "Diseño de la home de la tienda online de P&G España, para mejorar las conversiones y disminuir el abandono en la landing.",
  "purpose_procter2": "Se analizó la landing que utilizaban y detectamos 3 principales problemas: 1. Los usuarios no entendían de qué trataba la web, 2. no encontraban los beneficios de utilizar su tienda en vez de comprar en los supermercados, 3. no sabían cómo acceder a los productos. A partir de estos inputs se diseñó la nueva landing y se testeó con el programa ",
  "purpose_procter3": "Nos permitió detectar fallos de usabilidad cómo: -algunos usuarios clicaban elementos no clicables, -la explicación de las ofertas estaba muy abajo de la landing y los usuarios no hacían tanto scroll.",
  "info_puntoyseguido1": "Puntoyseguido es un proyecto académico realizado con 3 compañeros.",
  "info_puntoyseguido2": "Puntoyseguido es un proyecto para creativos de Barcelona con pocos recursos económicos , quienes necesitan aprender de forma económica distintas funciones de un software que utilizan en el ámbito estudiantil y/o profesional. Puntoyseguido es una plataforma social creada a partir de anuncios de usuarios que permite el intercambio de conocimientos a cambio de una comida, una cena o una caña. La propuesta es facilitar el contacto entre creativos para intercambiar conocimientos a través de los cursos que ellos mismos crean, económicos , directos y con contenidos específicos útiles.",
  "img_puntoyseguido1": "Página inicial",
  "img_puntoyseguido2": "Cursos que ofrece la plataforma",
  "img_puntoyseguido3": "Ficha ampliada del curso, con información del profesor",
  "img_puntoyseguido4": "Perfil del profesor",
  "img_puntoyseguido5": "Información de la plataforma",
  "img_puntoyseguido6": "Imágenes de diferentes test de usabilidad y cardsorting.",
  "purpose_puntoyseguido1": "Creación de una plataforma para favorecer el conocimiento entre creativos de una manera colaborativa",
  "purpose_puntoyseguido2": "El proceso de trabajo se realizó en 3 ejes que se trabajaron con metodología agile y scrum:",
  "puntoyseguido_step1": "Investigar, entrevistar y definir a nuestro usuario y sus necesidades.",
  "puntoyseguido_step2": "Realizar el diseño de la plataforma y testear con usuarios las nuevas implementaciones.",
  "puntoyseguido_step3": "Maquetar a nivel frontend la plataforma para poder lanzarla.",
  "process_work": "Para más información sobre el proceso de trabajo: ",
  "memory_project": "Memoria del proyecto final de máster",
  "title_tecnic_puntoyseguido1": "Entrevistas y encuestas. ",
  "title_tecnic_puntoyseguido2": "Cardsorting. ",
  "title_tecnic_puntoyseguido3": "Test usabilidad. ",
  "tecnic_puntoyseguido1": "Se realizaron diferentes entrevistas para definir qué problemática tenían los creativos para formarse, y qué tipo de público le interesaría una propuesta como la nuestra.",
  "tecnic_puntoyseguido2": "Hicimos diferentes test donde los usuarios ordenaban la información de los cursos. Se obtuvo diferentes inputs en cuanto a qué información era imprescindible.",
  "tecnic_puntoyseguido3": "Cada una de las historias de usuario definidas en los sprints, se testearon y se modificaron acorde con las conclusiones de los test.",
  "saltin_banquin_info1": "Saltinbanquin se dedica a la venta de zapatos para niños en España. Se dedicaban también a la venta física, pero actualmente solamente se dedican al medio online. Destacan por ser zapatos de alta calidad y producidos en España.",
  "saltin_banquin_info2": "Se me encargó realizar un test de usabilidad, y proponer un rediseño de la plataforma.", 
  "saltin_banquin_info3": "Web antes del Rediseño: ",
  "img_saltinbanquin1": "Ficha de producto",
  "img_saltinbanquin2": "Catálogo",
  "img_saltinbanquin3": "Página de error",
  "img_saltinbanquin4": "Página de histórico de pedidos",
  "img_saltinbanquin5": "Página de contacto",
  "img_saltinbanquin6": "Página adaptable a todos los dispositivos",
  "purpose_saltinbanquin": "Se realizó un test de usabilidad para detectar los principales problemas con los que contaba la plataforma. Los más importantes eran:",
  "saltinbanquin_step1": "Mala jerarquización de la información y de las acciones prioritarias de la plataforma",
  "saltinbanquin_step2": "Diseño desactualizado, con imágenes y composiciones antiguas.",
  "saltinbanquin_step3": "Aumentar las conversiones desde tablet/móvil realizando un diseño adaptable a todos los dispositivos.",
  "smartlink_info1": "Smartlink es una herramienta para analizar el estado de los productos en los supermercados de las marcas de gran consumo. Analiza los productos que están fuera de estock, los precios en los supermercados, las imágenes, la posición en el catálogo...",
  "smartlink_info2": "Smartlink es la herramienta que facilita a las empresas tener conocimiento sobre cómo están sus productos en los supermercados online, y les ayuda a saber qué acciones realizar para mejorar su visibilidad en los supermercados, y por lo tanto, mejorar sus ventas.",
  "img_smartlink1": "Dashboard inicial que muestra el estado de las diferentes submarcas en las categorías más importantes.",
  "img_smartlink2": "Página para definir los productos más importantes y realizar un análisi más constante de ellos.",
  "img_smartlink3": "Página de análisi de los precios de los productos.",
  "purpose_smartlink1": "Rediseño de las pantallas. Se trabajó a partir de la versión anterior que había estado en funcionamiento más de 2 años. Esto nos permitió tener mucha información sobre cómo los clientes utilizaban la plataforma, las peticiones que nos iban planteando, qué problemas le veíamos (desde usabilidad, responsive, programación, contenido, etc..) y poder plantear una propuesta que mejorara todos los inputs obtenidos.",
  "purpose_smartlink2": "Mi contribución en el proyecto se resume en 3 pasos:",
  "smartlink_step1": "Analizar qué información era importante para los clientes y de qué manera mostrarla. Definir qué métricas, análisis, datos, etc... eran relevantes para las marcas.",
  "smartlink_step2": "Realizar un nuevo diseño mejorando la usabilidad de la herramienta.",
  "smartlink_step3": "Maquetar a nivel frontEnd la plataforma, con HTMl5, CSS3, Boostrap y git.",
  "tedclothing_info1": "Tedclothing es una startup que se dedica a la impresión y venta de ropa fullprint a través de internet.",
  "tedclothing_info2": "Cuenta con diferentes estilos de ropa colorida para jóvenes. Los estampados están orientados a captar el interés de los jóvenes con imágenes llamativas, transgresoras o mensajes graciosos o reivindicativos.", 
  "img_tedclothing1": "Página inicial",
  "img_tedclothing2": "Ficha de producto",
  "img_tedclothing3": "Página de contacto",
  "img_tedclothing4": "Página del carrito de la compra",
  "img_tedclothing5": "Versión móvil",
  "img_tedclothing6": "Diseño de camisetas",
  "purpose_tedclothing": "Se realizó el proyecto desde 0 y abordé muchos aspectos diferentes en el proceso de creación de la marca y su lanzamiento.",
  "tedclothing_step1": "Se realizó un estudio de mercado para determinar cual era el estilo de ropa qué interesaba a los jóvenes. Realizamos diferentes test para detectar qué tipo de prendas eran más atractivas para los jóvenes. Desde hacer entrevistas, mostrar diferentes banners con diferentes tipo de prendas, medir qué prendas eran más visualizadas y cuales más vendidas...",
   "tedclothing_step2": "Diseño de los estampados de las prendas.",
  "tedclothing_step3": "Realización de la identidad corporativa de la marca, desde el logotipo, elementos publicitarios, etc.",
  "tedclothing_step4": "Difusión de la marca en las redes sociales.",
  "tedclothing_step5": "Diseño de la tienda online. Se realizaron test de usuario para validar las funcionalidades.",
  "trenes_info1": "Maqueta de trenes. ",
  "trenes_info2": "Proyecto familiar de contruir y decorar una maqueta de 9 x 3 metros. Es un proyecto personal que empezó en el año 2000 a partir de la pasión de mi padre por los trenes. El se dedica a la electricidad de la maqueta y yo a la decoración.", 
  "img_trenes1": "Decoración de casa de pastores con huerta",
  "img_trenes2": "Conjunto de casas",
  "img_trenes3": "Ampliación huerta",
  "img_trenes4": "Estación máquinas de carbón",
  "img_trenes5": "Vía del tren con casa del vigilante",
  "img": "Imágenes",

  "xerpa_info1": "CityXerpa es una aplicación que se encarga de llevar cualquier producto de un punto a otro. Permite llevar comida de restaurantes, flores, productos del supermercado.. cualquier cosa que necesites a un lugar en concreto.",
  "xerpa_info2": "CityXerpa es una app que nace en Andorra y actualmente se está extendiendo en España.", 
  "img_xerpa1": "Home // Menú // Registro",
  "img_xerpa2": "Lista de restaurantes // Lista de productos con foto // Lista de productos sin foto",
  "img_xerpa3": "Error 404 // Pago // Pedido recibido",
  "purpose_xerpa1": "Diseño de la app para android y IOS.",
  "purpose_xerpa2": "Se realizaron diferentes wireframes de baja fidelidad para entender el proceso de compra y testar el proceso con los usuarios.Se realizaron los diseños de todas las pantallas y se creó un prototipo funcional para testear la aplicación.",
};


};

window.changeLang = function (lang) {
  var body = document.getElementsByTagName('body')[0];
  var html = body.innerHTML;

  var regx, i;
  if (actualI18n) {
    var actual = i18n[actualI18n];
    var keysActual = Object.keys(actual);
    for (i = 0; keysActual.length > i; i++) {
      regx = new RegExp(i18n[actualI18n][keysActual[i]], 'mig');
      html = html.replace(regx, i18n[lang][keysActual[i]]);
    }
  } else {
    var keys = Object.keys(i18n[lang]);
    for (i = 0; keys.length > i; i++) {
      regx = new RegExp('{{' + keys[i] + '}}', 'mig');
      html = html.replace(regx, i18n[lang][keys[i]]);
    }
  }

  body.innerHTML = html;
  actualI18n = lang;
};

$(document).ready(function() {
  changeLang('es');

	// $.get('./lang/es.json', function(data) {
  //   console.log(data);
  // });
});
